### ISSUE TITLE
Broken link to introduction

### ISSUE THREAD

**Issue by abulvenz** [RonJeffries/scriv-git-pages#3]
On 01.md the introduction is linked as 00.html or 00.md.
It has been moved to index.html or just /

Thanks for sharing.

**Comment by RonJeffries** [comment]
Well spotted. I think I've fixed it. Thanks!

> On Aug 28, 2018, at 5:37 PM, abulvenz <notifications@github.com> wrote:
> 
> On 01.md the introduction is linked as 00.html or 00.md.
> It has been moved to index.html or just /
> 
> Thanks for sharing.
> 


Ron Jeffries
ronjeffries.com <http://ronjeffries.com/>
In times of stress, I like to turn to the wisdom of my Portuguese waitress,
who said: "Olá, meu nome é Marisol e eu serei sua garçonete."
